Home/urls.py
from django.urls import path
from . import views
app_name = 'Home'

urlpatterns = [
    path('', views.home, name="index"),
    path('india/', views.india, name="india"),
    path('world/', views.world, name="world"),
    path('entertainment/', views.entertainment, name="entertainment"),
    path('life_style/', views.life_style, name="life_style"),
    path('sports/', views.sports, name="sports"),
    path('Technology/', views.technology, name="technology"),
    path('business/', views.business, name="business")
]

Newsy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
]

Home/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render
from bs4 import BeautifulSoup as soup
from urllib.request import Request, urlopen as ureq
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

#opening urls
def open_page(url):
    request = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    uClient = ureq(request)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser", from_encoding="iso-8859-1")
    return page_soup

# Home scrapping functions
def scraptmi():
    page_soup = open_page("https://timesofindia.indiatimes.com/")
    container = page_soup.find("div", {"class": "top-story"})
    news = container.find_all('li')
    key = {}
    for headline in news:
        s = headline.a["href"]
        if s.startswith("/"):
            s="https://timesofindia.indiatimes.com"+s
        key[headline.a.text] = s

    return key.items()

def scraphindu():
    page_soup = open_page("https://www.thehindu.com/")
    container = page_soup.find("div", {"class": "main"})
    data = container.find_all("div", {"class": "story-card-news"})
    key = {}
    for headline in data:
        key[headline.h2.a.text] = headline.h2.a["href"]
    return key.items()

def scrapndtv():
    page_soup = open_page("https://www.ndtv.com/")
    container = page_soup.find("div", {"class": "cont_cmn top-stories-68"})
    news = container.find_all('li')
    key = {}
    for headline in news:
        a = headline.find('a', {"class": "item-title"})
        key[a.text] = a["href"]
        #key.append(a.text + "*&*" + a["href"])
    return key.items()

def scrapindexp():
    page_soup = open_page("https://indianexpress.com/")
    key= {}
    container = page_soup.find_all("div", {"class": "l-grid__item one-half@medium+"})
    for i in range(0, 2):
        news = container[i].find_all('div', {"class": "l-grid__item l-grid__item--divided one-half@small m-read-article"})
        for headline in news:
            key[headline.a["title"]] = headline.a["href"]
    return key.items()

def scrapht():
    page_soup = open_page("https://www.hindustantimes.com/")
    container = page_soup.find("div", {"class": "latestnews-left"})
    data = container.find_all("li")
    key = {}
    for headline in data:
        key[headline.h2.a.text] = headline.h2.a["href"]
    return key.items()

def scraptnews18():
    page_soup = open_page("https://www.news18.com/")
    key = {}
    container = page_soup.find("ul", {"class": "lead-mstory"})
    data = container.find_all("li")
    for headline in data:
        key[headline.a.text] = headline.a["href"]
    return key.items()

#India scrapping functions

def indiatmi():
    page_soup = open_page("https://timesofindia.indiatimes.com/india")
    container = page_soup.find("div", {"class": "main-content"})
    news = container.find("ul", {"class": "top-newslist clearfix"})
    key = {}
    for headline in news:
        s = headline.a["href"]
        if s.startswith("/"):
            s = "https://timesofindia.indiatimes.com" + s
        key[headline.a["title"]] = s

    news2 = container.find("ul", {"class": "list5 clearfix"})

    for headline2 in news2:
        s = headline2.a["href"]
        if s.startswith("/"):
            s = "https://timesofindia.indiatimes.com" + s
        key[headline2.a.text] = s
    return key.items()
def indiahindu():
    page_soup = open_page("https://www.thehindu.com/news/national/")
    container = page_soup.find("div", {"class": "justin-100x3-container hidden-xs"})
    # print(container)
    data = container.find_all("ul")
    key = {}
    for ss in data:
        x = ss.find_all("li")
        for z in x:
            s = z.h3.a.text.strip().split("\n")
            try:
                key[s[2]] = z.h3.a["href"]
            except IndexError:
                continue
    return key.items()
def indiaht():
    page_soup = open_page("https://www.hindustantimes.com/india-news/")
    container = page_soup.find("div", {"class": "col-sm-7 col-md-8 col-lg-9"})
    data = container.findAll("li")
    key = {}
    for i in range(0, 11):
        key[data[i].img["alt"]] = data[i].a["href"]
    return key.items()
def indiaindexp():
    page_soup = open_page("https://indianexpress.com/section/india/")
    container = page_soup.find("div", {"class": "a-pt5"})
    data = container.find_all("div", {"class": "l-grid__item l-grid__item--divided"})
    key = {}
    for head in data:
        key[head.h3.a.text] = head.h3.a["href"]
    return key.items()
def indiandtv():
    page_soup = open_page("https://www.ndtv.com/india?pfrom=home-mainnavgation")
    container = page_soup.find("div", {"class": "new_storylising"})
    data = container.findAll("div", {"class": "nstory_header"})
    key = {}
    for i in range(0, 11):
        key[data[i].a.text.strip()] = data[i].a["href"]
    return key.items()
def indianews18():
    page_soup = open_page("https://www.news18.com/india/?ref=topnav")
    container = page_soup.find("div", {"class": "blog-list"})
    data = container.findAll("div", {"class": "blog-list-blog"})
    key ={}
    for i in range(0, 11):
        key[data[i].a.img["alt"]] = data[i].a["href"]
    return key.items()

#World scrapping functions
def worldtmi():
    page_soup =open_page("https://timesofindia.indiatimes.com/world")
    container = page_soup.find("div", {"class": "top-newslist"})
    data = container.find_all("li")
    key = {}
    for head in data:
        s = head.a["href"]
        if s.startswith("/"):
            s = "https://timesofindia.indiatimes.com" + s
        key[head.a["title"]] = s
    return key.items()
def worldht():
    page_soup = open_page("https://www.hindustantimes.com/world-news/")
    container = page_soup.find("ul", {"class": "latest-news-morenews more-latest-news more-separate newslist-sec"})
    head = container.find_all("li")
    key = {}
    for i in range(0, 11):
        key[head[i].img["title"]] = head[i].a["href"]
    return key.items()
def worldndtv():
    page_soup = open_page("https://www.ndtv.com/world-news?pfrom=home-mainnavgation")
    container = page_soup.find("div", {"class": "newins_widmid"})
    head = container.find_all("div", {"class": "description"})
    key = {}
    for data in head:
       key[data.a.text] = data.a["href"]
    return key.items()
def worldnews18():
    page_soup = open_page("https://www.news18.com/world/?ref=topnav")
    container = page_soup.find("div", {"class": "hotTopic clearfix"})
    head = container.find_all("li")
    key = {}
    for data in head:
        key[data.a.text] = data.a["href"]
    return key.items()
def worldindexp():
    page_soup = open_page("https://indianexpress.com/section/world/")
    container = page_soup.find("div", {"class": "a-pt5"})
    data = container.find_all("div", {"class": "l-grid__item l-grid__item--divided"})
    key = {}
    for head in data:
        key[head.a["title"]] = head.a["href"]
    return key.items()
def worldhindu():
    page_soup = open_page("https://www.thehindu.com/news/international/")
    container = page_soup.find_all("div", {"class": "main"})
    content = container[3].find_all("div", {"class": "story-card-news"})
    key = {}
    for head in content:
        key[head.h3.a.text] = head.h3.a["href"]
    return key.items()

#Entertainment scrapping functions
def etmi():
    page_soup = open_page("https://timesofindia.indiatimes.com/etimes")
    container = page_soup.find("div", {"id": "homeatfmovieswidget"})
    content = container.find("ul", {"class": "ent_music_listing"})
    data = content.find_all("li")
    key = {}
    for i in range(0, 12):
        s = data[i].a["href"]
        if s.startswith("/"):
            s = "https://timesofindia.indiatimes.com" + s
        key[data[i].a["title"]] = s
    return  key.items()
def eht():
    page_soup = open_page("https://www.hindustantimes.com/entertainment/")
    container = page_soup.find("ul", {"class": "latest-news-morenews more-latest-news more-separate newslist-sec"})
    head = container.find_all("li")
    key = {}
    for i in range(0, 11):
        key[head[i].img["title"]] = head[i].a["href"]
    return key.items()
def enews18():
    page_soup = open_page("https://www.news18.com/movies/?ref=topnav")
    container = page_soup.find("div", {"class": "hotTopic clearfix"})
    head = container.find_all("li")
    key = {}
    for data in head:
        key[data.a.text] = data.a["href"]
    return key.items()
def eindexp():
    page_soup = open_page("https://indianexpress.com/section/entertainment/")
    container = page_soup.find("div", {"class": "a-pt5"})
    data = container.find_all("div", {"class": "l-grid__item l-grid__item--divided"})
    key = {}
    for head in data:
        key[head.a["title"]] = head.a["href"]
    return key.items()
def endtv():
    page_soup = open_page("https://gadgets.ndtv.com/entertainment")
    container = page_soup.find("div", {"class": "nlist bigimglist"})
    data = container.findAll("li")
    key = {}
    for i in range(0, 8):
        key[data[i].a.text] = data[i].a["href"]
    return key.items()
def ehindu():
    page_soup  = open_page("https://www.thehindu.com/entertainment/")
    container =page_soup.find("section",{"id":"section_2"})
    data=container.findAll("p",{"class":"story-card-33-heading"})
    key = {}
    for i in range(0,4):
        key[data[i].a.text] = data[i].a["href"]
    return key.items()

#Life Style scrapping functoins
def lifetmi():
    page_soup = open_page("https://timesofindia.indiatimes.com/etimes")
    container = page_soup.find("div", {"id": "homeatflifewidget"})
    content = container.find("ul", {"class": "ent_music_listing"})
    data = content.find_all("li")
    key = {}
    for i in range(0, 12):
        s = data[i].a["href"]
        if s.startswith("/"):
            s = "https://timesofindia.indiatimes.com" + s
        key[data[i].a["title"]] = s
    return key.items()
def lifenews18():
    page_soup = open_page("https://www.news18.com/lifestyle/?ref=topnav")

Home/templates/Home/base.html
<html>
<head>
<title>Newsy- Platform for news </title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'><link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" type="text/css" rel="stylesheet">
{% load staticfiles %}
    <script src="{% static 'Home/myscript.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'Home/mystyle.css' %}"/>
    <script>
$(document).ready(function(){
    $("#searchBox").keypress(function(event) {
    if (event.which == 13) {
        search();
     }
});
    $('[data-toggle="popover"]').popover({
        placement : 'top',
        trigger : 'hover'
    });
});
</script>
</head>
<body>
	<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<a class="navbar-brand" href="#"> Newsy </a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNav">
		<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="topNav">
		<ul class="navbar-nav">
		<li class="nav-item">
		<a class="nav-link" href="{% url 'Home:index' %}">
		<i class="fas fa-home"></i> Home</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="{% url 'Home:india' %}"><i class="far fa-flag"></i>  India &nbsp</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="{% url 'Home:world' %}"><i class="fas fa-globe"></i>  World &nbsp	</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="{% url 'Home:entertainment' %}"><i class="fas fa-headphones-alt"></i>  Entertainment &nbsp</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="{% url 'Home:business' %}"><i class="fas fa-business-time"></i>  Business &nbsp</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="{% url 'Home:sports' %}"><i class="fas fa-football-ball"></i>  Sports &nbsp</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="{% url 'Home:life_style' %}"><i class="fas fa-heart"></i>  Life Style &nbsp</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="{% url 'Home:technology' %}"><i class="fas fa-book"></i>  Technology &nbsp</a>
		</li>
		</ul>
		<ul class="nav navbar-nav ml-auto">
		<li class="nav-item">
		<input class="form-control" type="text" id="searchBox" placeholder="Search">
		</li>
		<li>
		<button class="btn btn-success" onclick="search()">Search</button>
		</li>
		</ul>
		</div>
	</nav>
{% block body %}
{% endblock %}
</body>
</html>

Home/templates/Home/index.html
{% extends 'Home/base.html' %}

{% block body %}
{% load custom_filter %}
    {% load staticfiles %}
<div class="container ">
<div class="row ">
        <div class="col-sm-5 newsBox">
        <div>
            <h4><img id="logo1" src="{% static 'Home/images/toi.png' %}">Times Of India <i class="fas fa-angle-double-right"></i></h4><hr/>
        </div>
        <div class="scrollable">
            <ul class="fa-ul">
                {% for key,value in tmi %}
                <li><span class="fa-li"><i class="fas fa-share"></i></span>&nbsp <a href="{{ value }}" target="_blank" title="{{ key }}">{{ key }}</a> </li>
                    {% endfor %}
            </ul>
        </div>
        </div>
        <div class="col-sm-5 newsBox">
                <div>
            <h4><img id="logo1" src="{% static 'Home/images/hindu.png' %}">The Hindu <i class="fas fa-angle-double-right"></i></h4><hr/>
        </div>
        <div class="scrollable">
            <ul class="fa-ul">
                      {% for key,value in hindu %}
                <li><span class="fa-li"><i class="fas fa-share"></i></span>&nbsp <a href="{{ value }}" target="_blank">{{ key }}</a> </li>
                    {% endfor %}
                </ul>
        </div>
        </div></div>
<div class="row">
        <div class="col-sm-5 newsBox">
                <div>
            <h4><img id="logo1" src="{% static 'Home/images/htc.png' %}">Hindustan Times <i class="fas fa-angle-double-right"></i></h4><hr/>
        </div>
        <div class="scrollable">
            <ul class="fa-ul">
                     {% for key,value in ht %}
                <li><span class="fa-li"><i class="fas fa-share"></i></span>&nbsp <a href="{{ value }}" target="_blank">{{ key }}</a> </li>
                    {% endfor %}
                </ul>
        </div>
        </div>
        <div class="col-sm-5 newsBox">
                <div>
            <h4><img id="logo1" src="{% static 'Home/images/ndtv.png' %}">NDTV <i class="fas fa-angle-double-right"></i></h4><hr/>
        </div>
        <div class="scrollable">
            <ul class="fa-ul">
                     {% for key,value in ndtv %}
                <li><span class="fa-li"><i class="fas fa-share"></i></span>&nbsp <a href="{{ value }}" target="_blank">{{ key }}</a> </li>
                    {% endfor %}
                </ul>
        </div>
        </div></div>
        <div class="row">
        <div class="col-sm-5 newsBox">
                <div>
            <h4><img id="logo1" src="{% static 'Home/images/min.png' %}">News 18 <i class="fas fa-angle-double-right"></i></h4><hr/>
        </div>
        <div class="scrollable">
            <ul class="fa-ul">
                     {% for key,value in news18 %}
                <li><span class="fa-li"><i class="fas fa-share"></i></span>&nbsp <a href="{{ value }}" target="_blank">{{ key }}</a> </li>
                    {% endfor %}
                </ul>
        </div>
        </div>
        <div class="col-sm-5 newsBox">
                <div>
            <h4><img id="logo1" src="{% static 'Home/images/exp.png' %}">The Indian Express <i class="fas fa-angle-double-right"></i></h4><hr/>
        </div>
        <div class="scrollable">
            <ul class="fa-ul">
                     {% for key,value in indexp %}
                <li><span class="fa-li"><i class="fas fa-share"></i></span>&nbsp <a href="{{ value }}" target="_blank">{{ key }}</a> </li>
                    {% endfor %}
                </ul>
        </div>
        </div></div>
    </div>
    <footer>
	    <h5>Developed by:</h5>
	  <div class="names"> Hitesh chaurasia |
	    Abhishek kumar sharma |
	    Azharuddin ansari |
	    Shivam dashore |
	    Ajay roshan |<hr/></div>
    </footer>

{% endblock %}

Home/templates/Home/india.html
{%  extends 'Home/base.html' %}